# Generated by Django 5.1.1 on 2024-10-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_product_customuser_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
